spring:
  datasource:
    hikari:
      mysql:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/test?useSSL=false&&allowMultiQueries=true
        username: ENC[Fu9sG8qRC8kIweIS4Lhk2G69ZWTqXt+GyAhdzAorwE7uwXk2iUEfOqZtdnKcp/4+]
        password: ENC[8Kywn+mJcRbX7CFBlRnUsJes74ycM/3VDezaCd4elPruJK99yYwJvF9FC+ZSeLSE]
        pool-name: MYSQL_DB
        minimum-idle: 1
        maximum-pool-size: 5
      mariadb:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbc-url: jdbc:log4jdbc:mariadb://localhost:5306/test
        username: ENC[Fu9sG8qRC8kIweIS4Lhk2G69ZWTqXt+GyAhdzAorwE7uwXk2iUEfOqZtdnKcp/4+]
        password: ENC[8Kywn+mJcRbX7CFBlRnUsJes74ycM/3VDezaCd4elPruJK99yYwJvF9FC+ZSeLSE]
        pool-name: MARIADB_DB
        minimum-idle: 1
        maximum-pool-size: 5

sql:
  init:
    mysql:
      locations:
        - sql/schema-mysql.sql
        - sql/data-mysql.sql
    mariadb:
      locations:
        - sql/schema-mariadb.sql
        - sql/data-mariadb.sql

logging:
  level:
    jdbc.sqlonly: off
    jdbc.sqltiming: debug
    jdbc.audit: off
    jdbc.resultset: off
    jdbc.resultsettable: off
    jdbc.connection: off
