spring:
  datasource:
    hikari:
      mysql:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/test?allowMultiQueries=true&rewriteBatchedStatements=true
        username: ENC[Fu9sG8qRC8kIweIS4Lhk2G69ZWTqXt+GyAhdzAorwE7uwXk2iUEfOqZtdnKcp/4+]
        password: ENC[8Kywn+mJcRbX7CFBlRnUsJes74ycM/3VDezaCd4elPruJK99yYwJvF9FC+ZSeLSE]
        pool-name: MYSQL_DB
        idle-timeout: 10000 # 기본값 600000 (10분)
        connection-timeout: 30000 # 기본값 30000 (30초)
        minimum-idle: 5 # 기본값 maximum-pool-size와 같음
        maximum-pool-size: 10 # 기본값 10
        max-lifetime: 1800000 # 기본값 1800000 (30분)
      mariadb:
        driver-class-name: org.mariadb.jdbc.Driver
        jdbc-url: jdbc:mariadb://localhost:5306/test?allowMultiQueries=true&rewriteBatchedStatements=true
        username: ENC[Fu9sG8qRC8kIweIS4Lhk2G69ZWTqXt+GyAhdzAorwE7uwXk2iUEfOqZtdnKcp/4+]
        password: ENC[8Kywn+mJcRbX7CFBlRnUsJes74ycM/3VDezaCd4elPruJK99yYwJvF9FC+ZSeLSE]
        pool-name: MARIADB_DB
        idle-timeout: 10000 # 기본값 600000 (10분)
        connection-timeout: 30000 # 기본값 30000 (30초)
        minimum-idle: 5 # 기본값 maximum-pool-size와 같음
        maximum-pool-size: 10 # 기본값 10
        max-lifetime: 1800000 # 기본값 1800000 (30분)
