spring:
  datasource:
    hikari:
      mysql:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/test?useSSL=false&&allowMultiQueries=true
        username: ENC[jDU4bstvrEyFDhol5ziGFg==]
        password: ENC[rvy0JSKWX2S3Fau5AQZnIA==]
        pool-name: MYSQL_DB
        minimum-idle: 1
        maximum-pool-size: 5
      mariadb:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbc-url: jdbc:log4jdbc:mariadb://localhost:5306/test
        username: ENC[jDU4bstvrEyFDhol5ziGFg==]
        password: ENC[rvy0JSKWX2S3Fau5AQZnIA==]
        pool-name: MARIADB_DB
        minimum-idle: 1
        maximum-pool-size: 5

sql:
  init:
    mysql:
      locations:
        - sql/schema-mysql.sql
        - sql/data-mysql.sql
    mariadb:
      locations:
        - sql/schema-mariadb.sql
        - sql/data-mariadb.sql

logging:
  level:
    jdbc.sqlonly: off
    jdbc.sqltiming: debug
    jdbc.audit: off
    jdbc.resultset: off
    jdbc.resultsettable: off
    jdbc.connection: off
