spring:
  datasource:
    hikari:
      mysql:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        # 기존 jdbc-url에서 쿼리 수행 시간을 확인하려면 해당 옵선을 추가하면 됨
        # &profileSql=true
        jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/test?useSSL=false&&allowMultiQueries=true&rewriteBatchedStatements=true&profileSql=true
        username: ENC[Fu9sG8qRC8kIweIS4Lhk2G69ZWTqXt+GyAhdzAorwE7uwXk2iUEfOqZtdnKcp/4+]
        password: ENC[8Kywn+mJcRbX7CFBlRnUsJes74ycM/3VDezaCd4elPruJK99yYwJvF9FC+ZSeLSE]
        pool-name: MYSQL_DB
        idle-timeout: 10000 # 기본값 600000 (10분)
        connection-timeout: 30000 # 기본값 30000 (30초)
        minimum-idle: 5 # 기본값 maximum-pool-size와 같음
        maximum-pool-size: 10 # 기본값 10
        max-lifetime: 1800000 # 기본값 1800000 (30분)
      mariadb:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        # 기존 jdbc-url에서 쿼리 Log를 확인하려면 해당 옵선을 추가하면 됨
        # &profileSql=true
        jdbc-url: jdbc:log4jdbc:mariadb://localhost:5306/test?allowMultiQueries=true&rewriteBatchedStatements=true&profileSql=true
        username: ENC[Fu9sG8qRC8kIweIS4Lhk2G69ZWTqXt+GyAhdzAorwE7uwXk2iUEfOqZtdnKcp/4+]
        password: ENC[8Kywn+mJcRbX7CFBlRnUsJes74ycM/3VDezaCd4elPruJK99yYwJvF9FC+ZSeLSE]
        pool-name: MARIADB_DB
        idle-timeout: 10000 # 기본값 600000 (10분)
        connection-timeout: 30000 # 기본값 30000 (30초)
        minimum-idle: 5 # 기본값 maximum-pool-size와 같음
        maximum-pool-size: 10 # 기본값 10
        max-lifetime: 1800000 # 기본값 1800000 (30분)

  jta:
    enabled: false
    atomikos:
      datasource:
        mysql:
          unique-resource-name: mysqlDataSource
          xa-data-source-class-name: com.mysql.cj.jdbc.MysqlXADataSource
          xa-properties:
            url: jdbc:mysql://localhost:3306/test?useSSL=false&&allowMultiQueries=true&rewriteBatchedStatements=true&profileSql=true
            user: ENC[Fu9sG8qRC8kIweIS4Lhk2G69ZWTqXt+GyAhdzAorwE7uwXk2iUEfOqZtdnKcp/4+]
            password: ENC[8Kywn+mJcRbX7CFBlRnUsJes74ycM/3VDezaCd4elPruJK99yYwJvF9FC+ZSeLSE]
        mariadb:
          unique-resource-name: mariadbDataSource
          xa-data-source-class-name: org.mariadb.jdbc.MariaDbDataSource
          xa-properties:
            url: jdbc:mariadb://localhost:5306/test?allowMultiQueries=true&rewriteBatchedStatements=true&profileSql=true
            user: ENC[Fu9sG8qRC8kIweIS4Lhk2G69ZWTqXt+GyAhdzAorwE7uwXk2iUEfOqZtdnKcp/4+]
            password: ENC[8Kywn+mJcRbX7CFBlRnUsJes74ycM/3VDezaCd4elPruJK99yYwJvF9FC+ZSeLSE]

sql:
  init:
    mysql:
      locations:
        - sql/schema-mysql.sql
        - sql/data-mysql.sql
    mariadb:
      locations:
        - sql/schema-mariadb.sql
        - sql/data-mariadb.sql

logging:
  level:
    jdbc.sqlonly: off
    jdbc.sqltiming: debug
    jdbc.audit: off
    jdbc.resultset: off
    jdbc.resultsettable: off
    jdbc.connection: off
