spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=Asia/Seoul
    username: ENC[jDU4bstvrEyFDhol5ziGFg==]
    password: ENC[rvy0JSKWX2S3Fau5AQZnIA==]

  sql:
    init:
      platform: mysql
      schema-locations: classpath:sql/schema-${spring.sql.init.platform}.sql
      data-locations: classpath:sql/data-${spring.sql.init.platform}.sql

logging:
  level:
    jdbc.sqlonly: off
    jdbc.sqltiming: debug
    jdbc.audit: off
    jdbc.resultset: off
    jdbc.resultsettable: off
    jdbc.connection: off
