### CommonService에서 예외
GET http://localhost:8080/api/common/ex

### BoardService에서 예외
GET http://localhost:8080/api/common/ex/board

### MemberService에서 예외
GET http://localhost:8080/api/common/ex/member
